version: '3'


services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres_db
      POSTGRES_DB: vinland
    volumes:
      - C:\dev\Vinland\pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vinland"]
      interval: 10s
      timeout: 5s
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mikasaa0101@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - db